/* building_neon_maps.js - generated by _dev/gen/map_building_neon.py (+ map_training_neon.py for training_enemy). */
var BUILDING_NEON_MAPS = {
  "version": 1,
  "frames": 9,
  "sprites": {
    "barracks_enemy": {
      "frameSize": {
        "w": 472,
        "h": 470
      },
      "frames": [
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.57262,
              "y": 0.23428,
              "rx": 0.03686,
              "ry": 0.03702,
              "rot": 0.0,
              "color": [
                87,
                129,
                119
              ],
              "alpha": 1.0,
              "phase": 0.1251,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.08804,
              "y": 0.46752,
              "rx": 0.02703,
              "ry": 0.01974,
              "rot": 0.0,
              "color": [
                85,
                135,
                123
              ],
              "alpha": 1.0,
              "phase": 0.7303,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.3282,
              "y": 0.15323,
              "rx": 0.02949,
              "ry": 0.02098,
              "rot": 0.0,
              "color": [
                87,
                139,
                124
              ],
              "alpha": 1.0,
              "phase": 0.6463,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "spot",
              "x": 0.22289,
              "y": 0.53632,
              "rx": 0.01398,
              "ry": 0.01404,
              "rot": 0.0,
              "color": [
                87,
                138,
                125
              ],
              "alpha": 1.0,
              "phase": 0.0869,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "spot",
              "x": 0.47063,
              "y": 0.20059,
              "rx": 0.01294,
              "ry": 0.013,
              "rot": 0.0,
              "color": [
                218,
                255,
                255
              ],
              "alpha": 1.0,
              "phase": 0.2612,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.38347,
              "y": 0.42356,
              "rx": 0.01142,
              "ry": 0.01146,
              "rot": 0.0,
              "color": [
                83,
                132,
                122
              ],
              "alpha": 1.0,
              "phase": 0.9251,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "spot",
              "x": 0.72692,
              "y": 0.46301,
              "rx": 0.01152,
              "ry": 0.01157,
              "rot": 0.0,
              "color": [
                99,
                138,
                123
              ],
              "alpha": 1.0,
              "phase": 0.4815,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "spot",
              "x": 0.11229,
              "y": 0.33191,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                87,
                140,
                125
              ],
              "alpha": 1.0,
              "phase": 0.8928,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.3072,
              "y": 0.36383,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                90,
                142,
                130
              ],
              "alpha": 1.0,
              "phase": 0.2614,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.65042,
              "y": 0.47021,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                255,
                238,
                170
              ],
              "alpha": 1.0,
              "phase": 0.2774,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 10,
              "kind": "spot",
              "x": 0.63559,
              "y": 0.13298,
              "rx": 0.00965,
              "ry": 0.00969,
              "rot": 0.0,
              "color": [
                88,
                129,
                117
              ],
              "alpha": 1.0,
              "phase": 0.7865,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 11,
              "kind": "spot",
              "x": 0.76483,
              "y": 0.46383,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                227,
                162,
                99
              ],
              "alpha": 1.0,
              "phase": 0.7441,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 12,
              "kind": "spot",
              "x": 0.38289,
              "y": 0.12069,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                86,
                137,
                121
              ],
              "alpha": 1.0,
              "phase": 0.7851,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.44073,
              "y": 0.30353,
              "rx": 0.07742,
              "ry": 0.03455,
              "rot": 0.0,
              "color": [
                99,
                140,
                126
              ],
              "alpha": 1.0,
              "phase": 0.8629,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.45536,
              "y": 0.16853,
              "rx": 0.03318,
              "ry": 0.0506,
              "rot": 0.0,
              "color": [
                114,
                174,
                154
              ],
              "alpha": 1.0,
              "phase": 0.9885,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.18415,
              "y": 0.52776,
              "rx": 0.03686,
              "ry": 0.02715,
              "rot": 0.0,
              "color": [
                95,
                146,
                133
              ],
              "alpha": 1.0,
              "phase": 0.5344,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "ring",
              "x": 0.32931,
              "y": 0.46532,
              "rx": 0.03564,
              "ry": 0.02715,
              "rot": 0.0,
              "color": [
                91,
                137,
                124
              ],
              "alpha": 1.0,
              "phase": 0.1285,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "spot",
              "x": 0.7305,
              "y": 0.46146,
              "rx": 0.01347,
              "ry": 0.01353,
              "rot": 0.0,
              "color": [
                99,
                138,
                123
              ],
              "alpha": 1.0,
              "phase": 0.4464,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.31578,
              "y": 0.3441,
              "rx": 0.01201,
              "ry": 0.01206,
              "rot": 0.0,
              "color": [
                85,
                132,
                120
              ],
              "alpha": 1.0,
              "phase": 0.5884,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "spot",
              "x": 0.55089,
              "y": 0.26608,
              "rx": 0.01121,
              "ry": 0.01126,
              "rot": 0.0,
              "color": [
                95,
                133,
                119
              ],
              "alpha": 1.0,
              "phase": 0.1611,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "spot",
              "x": 0.12767,
              "y": 0.49272,
              "rx": 0.01079,
              "ry": 0.01083,
              "rot": 0.0,
              "color": [
                86,
                127,
                114
              ],
              "alpha": 1.0,
              "phase": 0.9,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.27225,
              "y": 0.50671,
              "rx": 0.01035,
              "ry": 0.01039,
              "rot": 0.0,
              "color": [
                88,
                128,
                117
              ],
              "alpha": 1.0,
              "phase": 0.3005,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.76483,
              "y": 0.46383,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                227,
                162,
                99
              ],
              "alpha": 1.0,
              "phase": 0.7441,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.75468,
              "y": 0.47515,
              "rx": 0.17326,
              "ry": 0.10366,
              "rot": 0.0,
              "color": [
                105,
                157,
                139
              ],
              "alpha": 1.0,
              "phase": 0.098,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.68465,
              "y": 0.1457,
              "rx": 0.05161,
              "ry": 0.04443,
              "rot": 0.0,
              "color": [
                112,
                170,
                153
              ],
              "alpha": 1.0,
              "phase": 0.5551,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.26594,
              "y": 0.51084,
              "rx": 0.03318,
              "ry": 0.02715,
              "rot": 0.0,
              "color": [
                92,
                142,
                131
              ],
              "alpha": 1.0,
              "phase": 0.414,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "spot",
              "x": 0.47055,
              "y": 0.20273,
              "rx": 0.01541,
              "ry": 0.01547,
              "rot": 0.0,
              "color": [
                219,
                255,
                255
              ],
              "alpha": 1.0,
              "phase": 0.3394,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "bar",
              "x": 0.73684,
              "y": 0.57501,
              "rx": 0.02136,
              "ry": 0.01847,
              "rot": -2.5716,
              "color": [
                85,
                131,
                121
              ],
              "alpha": 1.0,
              "phase": 0.6607,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.19043,
              "y": 0.45351,
              "rx": 0.01471,
              "ry": 0.01477,
              "rot": 0.0,
              "color": [
                83,
                132,
                120
              ],
              "alpha": 1.0,
              "phase": 0.843,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "spot",
              "x": 0.46317,
              "y": 0.34443,
              "rx": 0.01182,
              "ry": 0.01187,
              "rot": 0.0,
              "color": [
                80,
                129,
                119
              ],
              "alpha": 1.0,
              "phase": 0.5044,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "spot",
              "x": 0.22403,
              "y": 0.31332,
              "rx": 0.01079,
              "ry": 0.01083,
              "rot": 0.0,
              "color": [
                80,
                129,
                118
              ],
              "alpha": 1.0,
              "phase": 0.8941,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.60699,
              "y": 0.10319,
              "rx": 0.01057,
              "ry": 0.01061,
              "rot": 0.0,
              "color": [
                93,
                145,
                136
              ],
              "alpha": 1.0,
              "phase": 0.5159,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.57262,
              "y": 0.08239,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                76,
                126,
                118
              ],
              "alpha": 1.0,
              "phase": 0.5402,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 10,
              "kind": "spot",
              "x": 0.59051,
              "y": 0.47931,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                79,
                129,
                122
              ],
              "alpha": 1.0,
              "phase": 0.2447,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.81145,
              "y": 0.57207,
              "rx": 0.07004,
              "ry": 0.04936,
              "rot": 0.0,
              "color": [
                93,
                142,
                130
              ],
              "alpha": 1.0,
              "phase": 0.0098,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "bar",
              "x": 0.45101,
              "y": 0.17193,
              "rx": 0.04553,
              "ry": 0.05409,
              "rot": 1.8311,
              "color": [
                103,
                149,
                132
              ],
              "alpha": 1.0,
              "phase": 0.0871,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.74868,
              "y": 0.46303,
              "rx": 0.04915,
              "ry": 0.02838,
              "rot": 0.0,
              "color": [
                227,
                162,
                99
              ],
              "alpha": 1.0,
              "phase": 0.6157,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "ring",
              "x": 0.4082,
              "y": 0.29853,
              "rx": 0.04055,
              "ry": 0.02838,
              "rot": 0.0,
              "color": [
                111,
                160,
                143
              ],
              "alpha": 1.0,
              "phase": 0.4797,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "spot",
              "x": 0.66194,
              "y": 0.54545,
              "rx": 0.0122,
              "ry": 0.01226,
              "rot": 0.0,
              "color": [
                81,
                130,
                120
              ],
              "alpha": 1.0,
              "phase": 0.1143,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.85526,
              "y": 0.47398,
              "rx": 0.01012,
              "ry": 0.01016,
              "rot": 0.0,
              "color": [
                255,
                238,
                170
              ],
              "alpha": 1.0,
              "phase": 0.6719,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "spot",
              "x": 0.46763,
              "y": 0.31974,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                227,
                162,
                102
              ],
              "alpha": 1.0,
              "phase": 0.6238,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.45052,
              "y": 0.194,
              "rx": 0.02703,
              "ry": 0.06787,
              "rot": 0.0,
              "color": [
                112,
                163,
                147
              ],
              "alpha": 1.0,
              "phase": 0.8954,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.74945,
              "y": 0.46371,
              "rx": 0.05284,
              "ry": 0.02962,
              "rot": 0.0,
              "color": [
                227,
                162,
                103
              ],
              "alpha": 1.0,
              "phase": 0.6454,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.41122,
              "y": 0.29839,
              "rx": 0.04424,
              "ry": 0.03209,
              "rot": 0.0,
              "color": [
                93,
                138,
                129
              ],
              "alpha": 1.0,
              "phase": 0.493,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "ring",
              "x": 0.84025,
              "y": 0.5493,
              "rx": 0.0553,
              "ry": 0.03826,
              "rot": 0.0,
              "color": [
                83,
                133,
                123
              ],
              "alpha": 1.0,
              "phase": 0.3493,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "ring",
              "x": 0.56198,
              "y": 0.47452,
              "rx": 0.02949,
              "ry": 0.03209,
              "rot": 0.0,
              "color": [
                88,
                140,
                126
              ],
              "alpha": 1.0,
              "phase": 0.8936,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "ring",
              "x": 0.18148,
              "y": 0.52775,
              "rx": 0.03564,
              "ry": 0.02591,
              "rot": 0.0,
              "color": [
                89,
                131,
                116
              ],
              "alpha": 1.0,
              "phase": 0.5177,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "ring",
              "x": 0.47982,
              "y": 0.31152,
              "rx": 0.03072,
              "ry": 0.02221,
              "rot": 0.0,
              "color": [
                93,
                137,
                123
              ],
              "alpha": 1.0,
              "phase": 0.3964,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "ring",
              "x": 0.30427,
              "y": 0.48269,
              "rx": 0.03441,
              "ry": 0.02591,
              "rot": 0.0,
              "color": [
                85,
                135,
                123
              ],
              "alpha": 1.0,
              "phase": 0.6138,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "ring",
              "x": 0.92736,
              "y": 0.4886,
              "rx": 0.02089,
              "ry": 0.02468,
              "rot": 0.0,
              "color": [
                91,
                132,
                118
              ],
              "alpha": 1.0,
              "phase": 0.6515,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.71744,
              "y": 0.58362,
              "rx": 0.01182,
              "ry": 0.01187,
              "rot": 0.0,
              "color": [
                78,
                127,
                117
              ],
              "alpha": 1.0,
              "phase": 0.8581,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 10,
              "kind": "spot",
              "x": 0.23087,
              "y": 0.53502,
              "rx": 0.0123,
              "ry": 0.01235,
              "rot": 0.0,
              "color": [
                85,
                131,
                118
              ],
              "alpha": 1.0,
              "phase": 0.0881,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 11,
              "kind": "spot",
              "x": 0.60561,
              "y": 0.50606,
              "rx": 0.01172,
              "ry": 0.01177,
              "rot": 0.0,
              "color": [
                85,
                134,
                123
              ],
              "alpha": 1.0,
              "phase": 0.3206,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 12,
              "kind": "spot",
              "x": 0.63551,
              "y": 0.53142,
              "rx": 0.011,
              "ry": 0.01105,
              "rot": 0.0,
              "color": [
                81,
                129,
                116
              ],
              "alpha": 1.0,
              "phase": 0.4366,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 13,
              "kind": "spot",
              "x": 0.69174,
              "y": 0.56383,
              "rx": 0.01035,
              "ry": 0.01039,
              "rot": 0.0,
              "color": [
                75,
                123,
                114
              ],
              "alpha": 1.0,
              "phase": 0.9729,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 14,
              "kind": "spot",
              "x": 0.56509,
              "y": 0.25378,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                227,
                162,
                99
              ],
              "alpha": 1.0,
              "phase": 0.7961,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 15,
              "kind": "spot",
              "x": 0.53237,
              "y": 0.27813,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                227,
                162,
                98
              ],
              "alpha": 1.0,
              "phase": 0.4908,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 16,
              "kind": "spot",
              "x": 0.66584,
              "y": 0.49515,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                86,
                127,
                113
              ],
              "alpha": 1.0,
              "phase": 0.289,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "spot",
              "x": 0.74479,
              "y": 0.46622,
              "rx": 0.03301,
              "ry": 0.03315,
              "rot": 0.0,
              "color": [
                227,
                162,
                105
              ],
              "alpha": 1.0,
              "phase": 0.7092,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.57062,
              "y": 0.25126,
              "rx": 0.02949,
              "ry": 0.02345,
              "rot": 0.0,
              "color": [
                90,
                140,
                126
              ],
              "alpha": 1.0,
              "phase": 0.7374,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.64196,
              "y": 0.20293,
              "rx": 0.03072,
              "ry": 0.02098,
              "rot": 0.0,
              "color": [
                91,
                134,
                119
              ],
              "alpha": 1.0,
              "phase": 0.3975,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "spot",
              "x": 0.2923,
              "y": 0.49406,
              "rx": 0.01423,
              "ry": 0.01429,
              "rot": 0.0,
              "color": [
                94,
                136,
                122
              ],
              "alpha": 1.0,
              "phase": 0.9584,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "spot",
              "x": 0.63653,
              "y": 0.46943,
              "rx": 0.01356,
              "ry": 0.01362,
              "rot": 0.0,
              "color": [
                227,
                162,
                104
              ],
              "alpha": 1.0,
              "phase": 0.1635,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.54996,
              "y": 0.36188,
              "rx": 0.01057,
              "ry": 0.01061,
              "rot": 0.0,
              "color": [
                95,
                146,
                130
              ],
              "alpha": 1.0,
              "phase": 0.6781,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "spot",
              "x": 0.20599,
              "y": 0.5411,
              "rx": 0.01012,
              "ry": 0.01016,
              "rot": 0.0,
              "color": [
                95,
                138,
                124
              ],
              "alpha": 1.0,
              "phase": 0.159,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "spot",
              "x": 0.60169,
              "y": 0.15745,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                81,
                124,
                117
              ],
              "alpha": 1.0,
              "phase": 0.4783,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.52601,
              "y": 0.06962,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                92,
                137,
                123
              ],
              "alpha": 1.0,
              "phase": 0.785,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.72388,
              "y": 0.49237,
              "rx": 0.13148,
              "ry": 0.09626,
              "rot": 0.0,
              "color": [
                101,
                159,
                143
              ],
              "alpha": 1.0,
              "phase": 0.5425,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "spot",
              "x": 0.27621,
              "y": 0.48661,
              "rx": 0.02543,
              "ry": 0.02554,
              "rot": 0.0,
              "color": [
                84,
                134,
                120
              ],
              "alpha": 1.0,
              "phase": 0.586,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.56479,
              "y": 0.0858,
              "rx": 0.05775,
              "ry": 0.03455,
              "rot": 0.0,
              "color": [
                89,
                142,
                129
              ],
              "alpha": 1.0,
              "phase": 0.6175,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "ring",
              "x": 0.65228,
              "y": 0.12061,
              "rx": 0.02949,
              "ry": 0.02838,
              "rot": 0.0,
              "color": [
                93,
                146,
                132
              ],
              "alpha": 1.0,
              "phase": 0.4342,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "ring",
              "x": 0.71751,
              "y": 0.1552,
              "rx": 0.03318,
              "ry": 0.02591,
              "rot": 0.0,
              "color": [
                91,
                142,
                126
              ],
              "alpha": 1.0,
              "phase": 0.1059,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "bar",
              "x": 0.20801,
              "y": 0.53507,
              "rx": 0.03322,
              "ry": 0.01847,
              "rot": -3.0164,
              "color": [
                93,
                137,
                122
              ],
              "alpha": 1.0,
              "phase": 0.9495,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "spot",
              "x": 0.3411,
              "y": 0.17086,
              "rx": 0.01685,
              "ry": 0.01692,
              "rot": 0.0,
              "color": [
                86,
                130,
                122
              ],
              "alpha": 1.0,
              "phase": 0.3737,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "ring",
              "x": 0.84357,
              "y": 0.46599,
              "rx": 0.01966,
              "ry": 0.02468,
              "rot": 0.0,
              "color": [
                227,
                162,
                96
              ],
              "alpha": 1.0,
              "phase": 0.3064,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.37992,
              "y": 0.42917,
              "rx": 0.01471,
              "ry": 0.01477,
              "rot": 0.0,
              "color": [
                94,
                148,
                135
              ],
              "alpha": 1.0,
              "phase": 0.1097,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.30675,
              "y": 0.15061,
              "rx": 0.0123,
              "ry": 0.01235,
              "rot": 0.0,
              "color": [
                80,
                129,
                118
              ],
              "alpha": 1.0,
              "phase": 0.4184,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 10,
              "kind": "spot",
              "x": 0.60377,
              "y": 0.1545,
              "rx": 0.011,
              "ry": 0.01105,
              "rot": 0.0,
              "color": [
                77,
                126,
                119
              ],
              "alpha": 1.0,
              "phase": 0.3828,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 11,
              "kind": "spot",
              "x": 0.30144,
              "y": 0.28664,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                79,
                127,
                117
              ],
              "alpha": 1.0,
              "phase": 0.3879,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 12,
              "kind": "spot",
              "x": 0.35323,
              "y": 0.31336,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                83,
                128,
                117
              ],
              "alpha": 1.0,
              "phase": 0.6877,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 13,
              "kind": "spot",
              "x": 0.15737,
              "y": 0.51005,
              "rx": 0.00915,
              "ry": 0.00919,
              "rot": 0.0,
              "color": [
                88,
                129,
                114
              ],
              "alpha": 1.0,
              "phase": 0.719,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "bar",
              "x": 0.44343,
              "y": 0.20103,
              "rx": 0.03214,
              "ry": 0.04221,
              "rot": 1.5715,
              "color": [
                97,
                145,
                129
              ],
              "alpha": 1.0,
              "phase": 0.1104,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.36728,
              "y": 0.26959,
              "rx": 0.05653,
              "ry": 0.04072,
              "rot": 0.0,
              "color": [
                89,
                139,
                123
              ],
              "alpha": 1.0,
              "phase": 0.1646,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.46599,
              "y": 0.1469,
              "rx": 0.02949,
              "ry": 0.01604,
              "rot": 0.0,
              "color": [
                108,
                158,
                140
              ],
              "alpha": 1.0,
              "phase": 0.2584,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "spot",
              "x": 0.36156,
              "y": 0.44448,
              "rx": 0.0165,
              "ry": 0.01657,
              "rot": 0.0,
              "color": [
                89,
                143,
                132
              ],
              "alpha": 1.0,
              "phase": 0.5602,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "spot",
              "x": 0.45563,
              "y": 0.32157,
              "rx": 0.01548,
              "ry": 0.01555,
              "rot": 0.0,
              "color": [
                227,
                162,
                101
              ],
              "alpha": 1.0,
              "phase": 0.6174,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.49952,
              "y": 0.2042,
              "rx": 0.01285,
              "ry": 0.01291,
              "rot": 0.0,
              "color": [
                83,
                129,
                114
              ],
              "alpha": 1.0,
              "phase": 0.5708,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "ring",
              "x": 0.80348,
              "y": 0.5744,
              "rx": 0.02458,
              "ry": 0.01974,
              "rot": 0.0,
              "color": [
                87,
                131,
                117
              ],
              "alpha": 1.0,
              "phase": 0.0468,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "spot",
              "x": 0.72692,
              "y": 0.46301,
              "rx": 0.01152,
              "ry": 0.01157,
              "rot": 0.0,
              "color": [
                99,
                138,
                123
              ],
              "alpha": 1.0,
              "phase": 0.4815,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.4958,
              "y": 0.30396,
              "rx": 0.01089,
              "ry": 0.01094,
              "rot": 0.0,
              "color": [
                87,
                128,
                116
              ],
              "alpha": 1.0,
              "phase": 0.2164,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.31144,
              "y": 0.34792,
              "rx": 0.01012,
              "ry": 0.01016,
              "rot": 0.0,
              "color": [
                88,
                142,
                126
              ],
              "alpha": 1.0,
              "phase": 0.7024,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 10,
              "kind": "spot",
              "x": 0.83849,
              "y": 0.54864,
              "rx": 0.01,
              "ry": 0.01005,
              "rot": 0.0,
              "color": [
                89,
                131,
                118
              ],
              "alpha": 1.0,
              "phase": 0.3141,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 11,
              "kind": "spot",
              "x": 0.76483,
              "y": 0.46383,
              "rx": 0.00953,
              "ry": 0.00957,
              "rot": 0.0,
              "color": [
                227,
                162,
                99
              ],
              "alpha": 1.0,
              "phase": 0.7441,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        },
        {
          "glows": [
            {
              "id": 0,
              "kind": "ring",
              "x": 0.72349,
              "y": 0.47699,
              "rx": 0.09216,
              "ry": 0.05923,
              "rot": 0.0,
              "color": [
                101,
                154,
                138
              ],
              "alpha": 1.0,
              "phase": 0.9743,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 1,
              "kind": "ring",
              "x": 0.31376,
              "y": 0.46862,
              "rx": 0.07496,
              "ry": 0.0543,
              "rot": 0.0,
              "color": [
                88,
                142,
                131
              ],
              "alpha": 1.0,
              "phase": 0.1546,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 2,
              "kind": "ring",
              "x": 0.68969,
              "y": 0.1418,
              "rx": 0.07004,
              "ry": 0.0543,
              "rot": 0.0,
              "color": [
                88,
                137,
                122
              ],
              "alpha": 1.0,
              "phase": 0.4425,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 3,
              "kind": "ring",
              "x": 0.84375,
              "y": 0.46676,
              "rx": 0.03441,
              "ry": 0.03702,
              "rot": 0.0,
              "color": [
                227,
                162,
                106
              ],
              "alpha": 1.0,
              "phase": 0.3356,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 4,
              "kind": "ring",
              "x": 0.2037,
              "y": 0.5306,
              "rx": 0.04301,
              "ry": 0.02345,
              "rot": 0.0,
              "color": [
                88,
                132,
                120
              ],
              "alpha": 1.0,
              "phase": 0.7587,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 5,
              "kind": "spot",
              "x": 0.60694,
              "y": 0.11208,
              "rx": 0.01699,
              "ry": 0.01706,
              "rot": 0.0,
              "color": [
                97,
                151,
                136
              ],
              "alpha": 1.0,
              "phase": 0.8424,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 6,
              "kind": "bar",
              "x": 0.90452,
              "y": 0.50616,
              "rx": 0.02267,
              "ry": 0.02243,
              "rot": 2.4865,
              "color": [
                90,
                143,
                130
              ],
              "alpha": 1.0,
              "phase": 0.1571,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 7,
              "kind": "spot",
              "x": 0.46807,
              "y": 0.20533,
              "rx": 0.01267,
              "ry": 0.01273,
              "rot": 0.0,
              "color": [
                218,
                255,
                255
              ],
              "alpha": 1.0,
              "phase": 0.4199,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 8,
              "kind": "spot",
              "x": 0.52542,
              "y": 0.06489,
              "rx": 0.0122,
              "ry": 0.01226,
              "rot": 0.0,
              "color": [
                90,
                143,
                133
              ],
              "alpha": 1.0,
              "phase": 0.6076,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 9,
              "kind": "spot",
              "x": 0.69553,
              "y": 0.36275,
              "rx": 0.01131,
              "ry": 0.01136,
              "rot": 0.0,
              "color": [
                81,
                131,
                119
              ],
              "alpha": 1.0,
              "phase": 0.6024,
              "pulse": 1.0,
              "sparkle": 0
            },
            {
              "id": 10,
              "kind": "spot",
              "x": 0.69288,
              "y": 0.42549,
              "rx": 0.01111,
              "ry": 0.01115,
              "rot": 0.0,
              "color": [
                82,
                131,
                120
              ],
              "alpha": 1.0,
              "phase": 0.8933,
              "pulse": 1.0,
              "sparkle": 0
            }
          ]
        }
      ]
    },
    "training_enemy": {
      "frameSize": {
        "w": 1154,
        "h": 848
      },
      "frames": [
        {
          "glows": [
            {
              "id": 0,
              "kind": "bar",
              "x": 0.6369,
              "y": 0.4928,
              "rx": 0.13473,
              "ry": 0.0065,
              "rot": 2.5805,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.2404,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 1,
              "kind": "bar",
              "x": 0.43964,
              "y": 0.57597,
              "rx": 0.20347,
              "ry": 0.00398,
              "rot": -2.5728,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.8009,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 2,
              "kind": "bar",
              "x": 0.69413,
              "y": 0.54564,
              "rx": 0.13328,
              "ry": 0.00607,
              "rot": 2.5757,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.604,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 3,
              "kind": "bar",
              "x": 0.57719,
              "y": 0.44727,
              "rx": 0.13641,
              "ry": 0.0055,
              "rot": 2.5772,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.3247,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 4,
              "kind": "bar",
              "x": 0.48598,
              "y": 0.36821,
              "rx": 0.13753,
              "ry": 0.00556,
              "rot": 2.5773,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.7128,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 5,
              "kind": "bar",
              "x": 0.43123,
              "y": 0.32173,
              "rx": 0.13721,
              "ry": 0.00538,
              "rot": 2.5784,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.8081,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 6,
              "kind": "bar",
              "x": 0.54482,
              "y": 0.3988,
              "rx": 0.11813,
              "ry": 0.00611,
              "rot": 2.5749,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.6244,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 7,
              "kind": "bar",
              "x": 0.78633,
              "y": 0.28683,
              "rx": 0.10471,
              "ry": 0.00509,
              "rot": -2.5728,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.8158,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 8,
              "kind": "bar",
              "x": 0.60838,
              "y": 0.1322,
              "rx": 0.06566,
              "ry": 0.00499,
              "rot": -2.574,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.89,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 9,
              "kind": "bar",
              "x": 0.15945,
              "y": 0.33178,
              "rx": 0.04929,
              "ry": 0.00513,
              "rot": 2.5751,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.4009,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 10,
              "kind": "bar",
              "x": 0.68539,
              "y": 0.63362,
              "rx": 0.03061,
              "ry": 0.00599,
              "rot": 2.5744,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.3098,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 11,
              "kind": "spot",
              "x": 0.92063,
              "y": 0.40393,
              "rx": 0.01344,
              "ry": 0.01828,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.5976,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 12,
              "kind": "spot",
              "x": 0.63205,
              "y": 0.19708,
              "rx": 0.01348,
              "ry": 0.01834,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.5491,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 13,
              "kind": "spot",
              "x": 0.83898,
              "y": 0.54507,
              "rx": 0.00996,
              "ry": 0.01356,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.7373,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 14,
              "kind": "bar",
              "x": 0.23134,
              "y": 0.6753,
              "rx": 0.02367,
              "ry": 0.0055,
              "rot": -2.5648,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.2682,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 15,
              "kind": "spot",
              "x": 0.7248,
              "y": 0.27095,
              "rx": 0.01181,
              "ry": 0.01608,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.8402,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 16,
              "kind": "spot",
              "x": 0.83767,
              "y": 0.36922,
              "rx": 0.0111,
              "ry": 0.0151,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.0515,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 17,
              "kind": "bar",
              "x": 0.44078,
              "y": 0.48843,
              "rx": 0.01549,
              "ry": 0.00572,
              "rot": 2.5953,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.0108,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 18,
              "kind": "spot",
              "x": 0.78073,
              "y": 0.31962,
              "rx": 0.01083,
              "ry": 0.01475,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.9075,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 19,
              "kind": "bar",
              "x": 0.64557,
              "y": 0.66801,
              "rx": 0.01474,
              "ry": 0.00573,
              "rot": 2.5737,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.9939,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 20,
              "kind": "spot",
              "x": 0.77815,
              "y": 0.59128,
              "rx": 0.00818,
              "ry": 0.01114,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.8912,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 21,
              "kind": "bar",
              "x": 0.83634,
              "y": 0.50342,
              "rx": 0.01213,
              "ry": 0.01389,
              "rot": 2.5649,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.9342,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 22,
              "kind": "spot",
              "x": 0.26783,
              "y": 0.2643,
              "rx": 0.00762,
              "ry": 0.01036,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.5491,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 23,
              "kind": "spot",
              "x": 0.57743,
              "y": 0.14199,
              "rx": 0.00965,
              "ry": 0.01313,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.0753,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 24,
              "kind": "spot",
              "x": 0.71884,
              "y": 0.28951,
              "rx": 0.00932,
              "ry": 0.01267,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.9823,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 25,
              "kind": "spot",
              "x": 0.32814,
              "y": 0.21423,
              "rx": 0.00686,
              "ry": 0.00934,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.1315,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 26,
              "kind": "spot",
              "x": 0.57238,
              "y": 0.16074,
              "rx": 0.00845,
              "ry": 0.01151,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.2435,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 27,
              "kind": "spot",
              "x": 0.7753,
              "y": 0.33534,
              "rx": 0.00814,
              "ry": 0.01108,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.8688,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 28,
              "kind": "spot",
              "x": 0.83275,
              "y": 0.38797,
              "rx": 0.00741,
              "ry": 0.01007,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.2217,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 29,
              "kind": "spot",
              "x": 0.16199,
              "y": 0.63624,
              "rx": 0.00499,
              "ry": 0.00679,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.6374,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 30,
              "kind": "spot",
              "x": 0.72759,
              "y": 0.59741,
              "rx": 0.00475,
              "ry": 0.00647,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.5398,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 31,
              "kind": "spot",
              "x": 0.71904,
              "y": 0.7365,
              "rx": 0.00491,
              "ry": 0.00669,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.6389,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 32,
              "kind": "spot",
              "x": 0.28308,
              "y": 0.7416,
              "rx": 0.00467,
              "ry": 0.00635,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.4423,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 33,
              "kind": "bar",
              "x": 0.47479,
              "y": 0.12742,
              "rx": 0.00874,
              "ry": 0.00354,
              "rot": -2.6122,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.5706,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 34,
              "kind": "spot",
              "x": 0.56937,
              "y": 0.87457,
              "rx": 0.00471,
              "ry": 0.00641,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.555,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 35,
              "kind": "spot",
              "x": 0.33885,
              "y": 0.24374,
              "rx": 0.00463,
              "ry": 0.0063,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.2495,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 36,
              "kind": "spot",
              "x": 0.27619,
              "y": 0.29732,
              "rx": 0.00428,
              "ry": 0.00582,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.8649,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 37,
              "kind": "spot",
              "x": 0.98294,
              "y": 0.50041,
              "rx": 0.00593,
              "ry": 0.00806,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.9323,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 38,
              "kind": "spot",
              "x": 0.43178,
              "y": 0.87593,
              "rx": 0.0045,
              "ry": 0.00612,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.583,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 39,
              "kind": "spot",
              "x": 0.0161,
              "y": 0.50009,
              "rx": 0.00441,
              "ry": 0.006,
              "rot": 0.0,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.4184,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 40,
              "kind": "bar",
              "x": 0.82564,
              "y": 0.69894,
              "rx": 0.00631,
              "ry": 0.00804,
              "rot": 2.5162,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.7454,
              "pulse": 1.28,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 41,
              "kind": "bar",
              "x": 0.75179,
              "y": 0.47568,
              "rx": 0.00679,
              "ry": 0.00731,
              "rot": 2.6115,
              "color": [
                255,
                46,
                40
              ],
              "alpha": 1.0,
              "phase": 0.8268,
              "pulse": 1.62,
              "sparkle": 0,
              "flicker": 0.5
            },
            {
              "id": 42,
              "kind": "spot",
              "x": 0.76531,
              "y": 0.46442,
              "rx": 0.00548,
              "ry": 0.00745,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.2827,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            },
            {
              "id": 43,
              "kind": "spot",
              "x": 0.74044,
              "y": 0.48631,
              "rx": 0.00479,
              "ry": 0.00652,
              "rot": 0.0,
              "color": [
                255,
                92,
                66
              ],
              "alpha": 1.0,
              "phase": 0.3618,
              "pulse": 1.95,
              "sparkle": 0,
              "flicker": 0.66
            }
          ]
        }
      ]
    }
  }
};
if (typeof window !== 'undefined') window.BUILDING_NEON_MAPS = BUILDING_NEON_MAPS;
if (typeof module !== 'undefined' && module.exports) module.exports = BUILDING_NEON_MAPS;
